# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: savelog

on:
  repository_dispatch:
    types: [savelog]
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false
jobs:
  build:
    runs-on: windows-2019

    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Unpack DiscordChatExporter.CLI
        run: Expand-Archive -Path DiscordChatExporter.CLI.zip

      - name: Export EU4日wiki:一般log
        run: |
          DiscordChatExporter.CLI/DiscordChatExporter.Cli.exe export -t "$($env:BOT_TOKEN)" -b -c 749876460155699323 -f HtmlDark -o docs/eu4jpwiki/eu4jpwiki_general_14day.html --after "$([DateTime]::Today.AddDays(-14).ToString('yyyy-MM-dd'))" 
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Export EU4日wiki:管理者連絡・質問log
        run: |
          DiscordChatExporter.CLI/DiscordChatExporter.Cli.exe export -t "$($env:BOT_TOKEN)" -b -c 749978066528501771 -f HtmlDark -o docs/eu4jpwiki/eu4jpwiki_admin_14day.html --after "$([DateTime]::Today.AddDays(-14).ToString('yyyy-MM-dd'))" 
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}


      - name: push translation
        run: |
          dir
          git config --global user.email "matanki.saito@gmail.com"
          git config --global user.name "matanki.saito"
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git add -A
          git commit -m "Save/Update files [ci skip]"
          git push origin HEAD:master
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
